dist: xenial
language: generic
sudo: required
branches:
  only:
    - master
addons:
  apt:
    packages:
      - python3
      - python3-pip
      - python3-setuptools
      - python3-wheel
      - libnl-route-3-dev
      - python3-dev
      - libvirt-dev
      - gcc
before_script:
  - pip3 install pyflakes pycodestyle
  - pip3 install -r requirements-test.txt
script:
  - make qa
  - pytest
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/911941efe0dfc645466f
    on_success: always  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always
