name: Building Koan packages

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build-debian-debs:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Build a Debian 10 Package
        shell: 'script -q -e -c "bash {0}"'
        run: |
          ./docker/debs/build-and-install-debs.sh deb10 docker/debs/debian/Debian10.dockerfile
