name: Building Koan packages

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build-centos8-rpms:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Build a CentOS 8 Package
        shell: 'script -q -e -c "bash {0}"'
        run: |
          ./docker/rpms/build-and-install-rpms.sh el8 docker/rpms/CentOS_8/CentOS8.dockerfile
  build-fedora34-rpms:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Build a Fedora 34 Package
        shell: 'script -q -e -c "bash {0}"'
        run: |
          ./docker/rpms/build-and-install-rpms.sh fc34 docker/rpms/Fedora_34/Fedora34.dockerfile
  build-opensuse-leap-rpms:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Build a openSUSE Leap 15.3 Package
        shell: 'script -q -e -c "bash {0}"'
        run: |
          ./docker/rpms/build-and-install-rpms.sh opensuse-leap docker/rpms/openSUSE_Leap_15.3/openSUSE_Leap_15.3.dockerfile
  build-opensuse-tumbleweed-rpms:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Build a openSUSE Tumbleweed Package
        shell: 'script -q -e -c "bash {0}"'
        run: |
          ./docker/rpms/build-and-install-rpms.sh opensuse-tumbleweed docker/rpms/openSUSE_Tumbleweed/openSUSE_TW.dockerfile
  build-debian-debs:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Build a Debian 10 Package
        shell: 'script -q -e -c "bash {0}"'
        run: |
          ./docker/debs/build-and-install-debs.sh deb10 docker/debs/debian/Debian10.dockerfile
