name: Linting Koan

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run_qa:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install pre reqs
        run: >-
          sudo apt-get install -y
          git
          tar
          python3-wheel
          python3-pip
          python3-libvirt
          make
      - name: Install dependencies
        run: pip3 install .[lint,test]
      - name: Run Linters
        run: make qa
  black:
    name: black formatter
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: psf/black@stable
        with:
          options: "--check --safe --verbose"
          version: "22.3.0"
