name: Testing Koan

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run_tests:
    runs-on: ubuntu-20.04
    container: registry.opensuse.org/opensuse/tumbleweed:latest
    steps:
      - name: Install pre reqs
        run: zypper -n in git tar
      - uses: actions/checkout@v2
      - name: Install package deps
        run: zypper -n in --no-recommends python3 python3-base python3-wheel python3-pip python3-libvirt-python python3-codecov make
      - name: Install dependencies
        run: pip3 install .[lint,test]
      - name: Run tests
        run: pytest --cov=./koan
      - name: Upload report to codecov
        run: codecov
